### PR TITLE
Add support for jpda in tomcat

### PR DESCRIPTION
**Pull request by mjalil**
Hi Camunda,
JPDA remote debugging in tomcat is a good debugging tool for Camunda extension developers

Thanks, Camunda

### CODE REVIEW

**Comment by menski** [comment]
Thanks for the PR. What is your opinion on allowing the user to specify the `catalina.sh` command instead? So the user has full control, i.e. instead of `ENABLE_JPDA` something like `CATALINA_CMD` which the user could set to `jpda run` to start with jpda.

**Comment by mjalil** [comment]
@menski, No. Camunda "Full distribution" don't use Catalina commands. So, I think Camunda docker neither would be required to use Catalina commands. for example, why should I start Camunda under a security manager (-security), or use "stop" or "start" commands, while I can start and stop the docker container. IMHO, "debug" command is also useless in docker context, we do not want to debug Camunda in the docker machine. remote debugging through JPDA is sufficient.
Also, I prefer to provide an explicit option like enable/disable JPDA instead of plain text that might pass wrong commands to Catalina, then you need to sanitize that plain text. plain text is also a security concern

By the way, YOU are the owner of this repo, whatever you want.

**Comment by menski** [comment]
> By the way, YOU are the owner of this repo, whatever you want.

Yeah but the opinion of users if more important for me. 

So I agree with the argument that an explicit flag is better then the general catalina commands approach. 

What I would like to do is to make this feature also work for Wildfly so it's a general option and not limited to Tomcat. Also the README should contain a description of the debug feature.

I will try to work on this in the near future. If you want to further contribute to this feature feel free to push more commits to your branch.

**Comment by mjalil** [comment]
thanks, @menski. I don't know anything about Wildfly, So I think it is better you continue the work.

**Comment by menski** [comment]
Hi @mjalil,

I extended your changes to also support wildfly and merged them with https://github.com/camunda/docker-camunda-bpm-platform/commit/9d52beee006fa8eecb9163cd79476c006ddd1c15. Thanks again for your contribution. :clap:

**Pull request closed without merging**
