### PR TITLE
Add env variables for database configuration 

### PR DESCRIPTION
**Pull request by AndreaGiardini**
This pull request adds the following environment variables:

`DB_CONN_MAXACTIVE`
`DB_CONN_MINIDLE`
`DB_CONN_MAXIDLE`

They have all been documented in the README

### CODE REVIEW

**Comment by AndreaGiardini** [comment]
I got these numbers by relying on this configuration file: https://github.com/camunda/camunda-bpm-platform/blob/master/distro/tomcat/assembly/src/conf/server.xml#L66

Let me know if you still prefer me to change them to the tomcat's defaults

I will try to have a look at wildfly soon

**Comment by menski** [comment]
Okay my fault, wasn't aware that we are already limiting these values, then of course you don't have to change anything :see_no_evil:

**Comment by AndreaGiardini** [comment]
I am no wildfly expert, but it looks like there is no equivalent option for wildfly. I could find only: `min-pool-size` and `max-pool-size`

I suggest:
 - `DB_CONN_MAXACTIVE` = `max-pool-size`
 - `DB_CONN_MINIDLE` = `min-pool-size`
 - `DB_CONN_MAXIDLE` : I can document in the readme that this option has no effect on wildfly

Would you be ok with that?

**Comment by menski** [comment]
Sounds okay to me

**Comment by AndreaGiardini** [comment]
Ready for review

**Comment by menski** [comment]
I merged the changes to all branchs, will take some time until all images are rebuilt.

**Pull request merged**
