### PR TITLE
Allow the script to be used with standard tomcat installations

### PR DESCRIPTION
**Pull request by ieugen**
* this patch allows the script to be used with docker tomcat image by specifying CATALINA_HOME variable

This will allow more flexibility when changing the tomcat distribution.

### CODE REVIEW

**Comment by ieugen** [comment]
Build failed because of download.
I have signed the CLA but it does not show ! I think there is an issue with this.

**Comment by AndreaGiardini** [comment]
Hello @ieugen 
Thank you for your contribution :)

Can you please click on the link contained in the CLAassistant message where it says `Let us recheck it.` ?

**Comment by ieugen** [comment]
I did sign it again: 
Captură de ecran de la 2019-09-24 08-01-03

**Comment by ieugen** [comment]
Maybe the CLA check is not triggered because of the failed build? Can you trigger the check manually?

**Comment by Langleu** [comment]
Hey @ieugen,
first of all thanks for the contribution!

The reason why the CLA check does not work is that the commit was done with the GitHub account @devlabel-machines . Meaning it will check for the permission of this account.
In case you committed with the wrong account you should either sign it with that account or recommit with @ieugen .

**Comment by ieugen** [comment]
Hi, 

I've fixed the license check. Thanks for bringing it to my attention.

Regards,
Eugen

**Comment by Langleu** [comment]
Hey @ieugen,
sorry for only coming back to you now.
Maybe you could explain me what you are trying to achieve?
It looks like you are trying to use your own tomcat version and I'm not quite sure yet whether we want to support that in the long run.

**Comment by ieugen** [comment]
I'm trying to use the script with https://github.com/docker-library/tomcat, (or other standalone instlals) without changing it.

**Comment by Langleu** [comment]
could you describe your problem a bit further and what you are trying to achieve?
Maybe a minimal working example would help to clarify things for me.
In general the change wouldn't break anything, but I'm trying to understand how you would use it and whether it should be documented.
The `camunda-tomcat.sh` is just the executable, meaning you also download camunda yourself?

**Comment by ieugen** [comment]
Well, 

The idea is to make it easy to build on the official tomcat (not built on top of the alpine tomcat image).

I made a custom Dockerfile and I'm using the script with the env variable to make things work out of the box. 

I figured this change will allow you (or others) to build camunda platforms on top of tomcat distributions that obey CATALINA_HOME - the official ones to to my knowledge.

Dockerfile
````
FROM gradle:5.6 as builder

RUN mkdir /camunda-build
WORKDIR /camunda-build

COPY build.gradle ./

RUN gradle clean build --info --stacktrace

FROM tomcat:9.0-jre8

ARG VERSION=7.11.0

ENV CAMUNDA_VERSION=${VERSION}
ENV DB_DRIVER=org.h2.Driver
ENV DB_URL=jdbc:h2:./camunda-h2-dbs/process-engine;MVCC=TRUE;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
ENV DB_USERNAME=sa
ENV DB_PASSWORD=sa
ENV DB_CONN_MAXACTIVE=20
ENV DB_CONN_MINIDLE=5
ENV DB_CONN_MAXIDLE=20
ENV DB_VALIDATE_ON_BORROW=false
ENV DB_VALIDATION_QUERY="SELECT 1"
ENV SKIP_DB_CONFIG=
ENV WAIT_FOR=
ENV WAIT_FOR_TIMEOUT=30
ENV TZ=UTC
ENV DEBUG=false
ENV JAVA_OPTS="-Xmx1024m -XX:MaxMetaspaceSize=256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

EXPOSE 8080 8000

# Copy camunda libs to tomcat lib https://hub.docker.com/_/tomcat
COPY --from=builder /camunda-build/build/distribution/lib /usr/local/tomcat/lib

# Copy camunda webapps to tomcat webapps/ directory
COPY --from=builder /camunda-build/build/distribution/webapps/ /usr/local/tomcat/webapps/

COPY bin /usr/local/bin
COPY catalina_home /usr/local/tomcat

RUN apt-get update \
    && apt-get install -y bash \
                       ca-certificates \
                       tzdata \
                       less \
                       xmlstarlet \
                   && apt-get clean \
                   && wget -O /usr/local/bin/wait-for-it.sh \
                     "https://raw.githubusercontent.com/vishnubob/wait-for-it/db049716e42767d39961e95dd9696103dca813f1/wait-for-it.sh" \
                   && chmod +x /usr/local/bin/wait-for-it.sh \
                   && rm -rf /usr/local/tomcat/webapps/examples

CMD ["/usr/local/bin/camunda.sh"]
```

I also think the current docker build for the platform could be simplified a bit.

I'm using gradle here to download all the dependencies and then copy them to the tomcat folder. 
I think it has some merits towards maintainability and visibility into what dependencies get packaged.

I'm sure a similar ting can be done with maven. To me it makes sense since the dependencies are published in Maven.

My build.gradle that I use to build a custom camunda platform with some custom war's. It could include other production fixes as well. 

```
plugins {
  id 'base'
}

configurations {
  distro
  tomcatLib
  webapp
}

ext {
  camundaVersion = '7.11.0'
  psiProbeVersion = '3.3.1'
}

dependencies {

  distro "org.camunda.bpm.tomcat:camunda-bpm-tomcat:${camundaVersion}@tar.gz"

  tomcatLib platform("org.camunda.bpm:camunda-bom:${camundaVersion}")

  tomcatLib "org.camunda.bpm.model:camunda-bpmn-model:${camundaVersion}"
  tomcatLib "org.camunda.bpm.model:camunda-cmmn-model:${camundaVersion}"
  tomcatLib "org.camunda.bpm.model:camunda-dmn-model:${camundaVersion}"

  tomcatLib("org.camunda.bpm:camunda-engine:${camundaVersion}") {
    exclude group: 'org.springframework'
    exclude group: 'com.google.code.gson'
  }

  tomcatLib "org.camunda.bpm:camunda-engine-plugin-spin:${camundaVersion}"
  tomcatLib "org.camunda.bpm:camunda-engine-plugin-connect:${camundaVersion}"

  tomcatLib "org.camunda.bpm.identity:camunda-identity-ldap:${camundaVersion}"

  tomcatLib 'org.camunda.connect:camunda-connect-connectors-all:1.2.1'
  tomcatLib 'org.camunda.template-engines:camunda-template-engines-freemarker:1.1.0'
  tomcatLib 'org.camunda.spin:camunda-spin-dataformat-all:1.7.1'

  tomcatLib "org.codehaus.groovy:groovy-all:2.4.17"
  tomcatLib "com.h2database:h2:1.4.199"
  tomcatLib "com.fasterxml.uuid:java-uuid-generator:3.2.0"
  tomcatLib "org.slf4j:slf4j-jdk14:1.7.26"

  // extra jars
  tomcatLib "org.postgresql:postgresql:42.2.8"
  tomcatLib "mysql:mysql-connector-java:8.0.17"

  distro "org.camunda.bpm.distro:camunda-sql-scripts:${camundaVersion}@tar.gz"

  webapp "org.camunda.bpm:camunda-engine-rest:${camundaVersion}:tomcat@war"
  webapp "org.camunda.bpm.webapp:camunda-webapp-tomcat:${camundaVersion}@war"
  webapp "org.camunda.bpm.distro:camunda-h2-webapp:${camundaVersion}@war"

  webapp "com.github.psi-probe:psi-probe-web:${psiProbeVersion}@war"
}

task copyDependencies(type: Copy) {

  from(configurations.distro)

  from(configurations.tomcatLib) {
    into 'lib'
  }

  from(configurations.webapp) {

    rename "camunda-webapp-tomcat-${camundaVersion}.war", "camunda.war"
    rename "camunda-engine-rest-${camundaVersion}-tomcat.war", "engine-rest.war"
    rename "camunda-h2-webapp-${camundaVersion}.war", "h2.war"

    rename "psi-probe-web-${psiProbeVersion}.war", "psi-probe.war"

    into 'webapps'
  }

  into 'build/distribution'
}

build.dependsOn 'copyDependencies'

repositories {
  mavenCentral()
  maven {
    url "https://app.camunda.com/nexus/content/repositories/camunda-bpm"
  }
  maven {
    url "https://app.camunda.com/nexus/content/repositories/camunda-bpm-snapshots"
  }
}
```

**Comment by Langleu** [comment]
Thanks for the example! Could maybe be useful if other people are trying to achieve the same.
I will keep your ideas in mind in case we optimize the image building at some point.
Once again sorry for the delay and thanks for the contribution!

**Review by Langleu — APPROVED** [review]
Thanks!

**Pull request merged**
