### PR TITLE
SRE 519: Security update build

### PR DESCRIPTION
**Pull request by lwille**
https://www.oracle.com/technetwork/security-advisory/cpuapr2019-5072813.html
https://www.oracle.com/technetwork/java/javase/8u212-relnotes-5292913.html

SRE-519

### CODE REVIEW

**Comment by menski** [comment]
@lwille what is the plan for this PR? Who should review it? Someone from the SRE team?

**Comment by lwille** [comment]
https://app.camunda.com/jira/browse/SRE-519

As mentioned in the ticket, for now we're just waiting for the alpine package openjdk8 to be updated and a new docker image to be published https://pkgs.alpinelinux.org/packages?branch=edge&repo=community&name=openjdk8

**Comment by menski** [comment]
Okay thanks for the update

**Comment by lwille** [comment]
`openjdk:8u212-jre-alpine3.9` is now available. I tested the build and it seems to be alright.

**Pull request merged**
