### PR TITLE
CAM-10193 - Optimize/Rewrite Docker Image

### PR DESCRIPTION
**Pull request by PhilippHeuer**
# Description
I started reworking the docker image to make a few modifications to run it on my kubernetes cluster.

I also made it easy to add other distributions / plugins like flyway, sso / or other db drivers.
Furthermore the scripts are using hooks, so it's easy to modify/extend the repo even if the upstream repo changes later on.

Are you interested in getting this merged back into your repository?

Link: https://github.com/PhilippHeuer/docker-camunda-bpm-platform

# Complete
- supports overwriting the base image (for users that have their own with custom certs / rhel / ?)
- supports flyway db migrations
- one dockerfile, scripts for different os families / distributions
- cleanup demo webapps
- use a more recent openjdk for the better container support
- do not download anything at runtime (like db. drivers or scripts in the old image)
- support for any os as long as the scripts are added (oraclelinux & alpine for now)
- supports kubernetes secret files for the db connection
- move the camunda installation into /app
- persist all data into /data (volumes)
- use wait_for_it to wait for for the database to be ready
- tests using https://github.com/aelsabbahy/goss
- support for single-sign-on providers (keycloak or others), configuration via environment

# In Progress
- configuration of all bpm properties (engine, executor, etc.) using env variables

# Planned
- add a little magic to hide the build args from the image for ee builds
- wildfly app server not supported right now
- JPDA support
- Maybe add goss for a health endpoint

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hi @PhilippHeuer,

Thank you for the contribution!

Due to the holidays, it may take a week or two until your PR is reviewed. However, I have already created a ticket on our issue tracker, so that you can track our progress more easily: https://app.camunda.com/jira/browse/CAM-10193

Best,
Nikola

**Comment by PhilippHeuer** [comment]
Okay thanks.

Just be aware that it's still a draft as it's still work in progress.
Some early feedback would be nice though.

**Comment by AndreaGiardini** [comment]
Hello @PhilippHeuer 

First of all, thank you for your contribution :)
I think this PR is too big to be merged as-is ( `+14,434 −892`)

Can you please close this PR and split it into several independent pull requests?
This will make the review process much smoother :)

**Comment by PhilippHeuer** [comment]
Sure, i can split it up into many small PR's and make a first one with just the base for the other changes.

The minimal change would be to have a single dockerfile to support having install scripts for different os families / distributions / plugins that can be added later on. I will create a new PR for that though.

Most of the changed lines were just the added SQL Files for automated db migration.

**Comment by AndreaGiardini** [comment]
Hello

I would rather create issues and discuss them individually since I am not sure if we want to merge all the changes that you proposed. Since I don't want you to do extra work for nothing feel free to submit your suggestions so that we can tackle them individually and put work on them only if we are sure that the PR is something that we really want.

In the meanwhile, I will close this pull request since we both agree that is too big to be handled as-is. It's important to say that maintaining retro compatibility is a priority when submitting changes to the docker images.

**Pull request closed without merging**
