### PR TITLE
chore(repo): rename Camunda BPM Platform to Camunda Platform

### PR DESCRIPTION
**Pull request by mboskamp**
Related to CAM-12950

### CODE REVIEW

**Review by yanavasileva — APPROVED** [review]
Looks good. Let's ping Infra for approval as well.

**Review by aabouzaid — APPROVED** [review]
LGTM, thank you :+1:

**Comment by mboskamp** [comment]
@aabouzaid thanks. I merged the PR. Sorry for the merge commit. I clicked the wrong button. I hope it's not a big deal. :(

**Comment by aabouzaid** [comment]
> @aabouzaid thanks. I merged the PR. Sorry for the merge commit. I clicked the wrong button. I hope it's not a big deal. :(

@mboskamp no worries, all good :+1: 
I don't recall that could make any issues at the moment, but it's not we cannot fix.

**Pull request merged**
