### PR TITLE
SRE-565 - Modifications to use Debian Stretch as base image.

### PR DESCRIPTION
**Pull request by chrismaeda**
My application requires GRPC.  GRPC uses netty-tcnative which does not work with alpine linux (cf. https://github.com/netty/netty-tcnative/issues/111).  Instead of building a custom netty-tcnative binary for alpine, I modified this base container to use Debian Stretch and to include the netty-tcnative-java package.

I don't expect you to merge this directly, but perhaps you could reorganize the source tree so that you have alpine and debian versions of the base containers?

### CODE REVIEW

**Comment by menski** [comment]
Hi @chrismaeda, thanks for raising this issue. I will think about how to structure the repository to provide alpine and debian images at the same time. But I can't promise on a time frame for this, sorry. If you have any proposals feel free to share them in this issue.

**Comment by chrismaeda** [comment]
The simplest approach seems to be a directory structure like this:

**Comment by chrismaeda** [comment]
The simplest approach seems to be a directory structure like this:

- alpine
-- Dockerfile for alpine
-- download.sh etc
- debian
-- Dockerfile for debian
-- download.sh etc

This duplicates the scripts but allows you to use the support in the 'docker build' commands for branches/tags and folders. E.g.

To build alpine: docker build myrepo.git#branchname:alpine
To build debian: docker build myrepo.git#branchname:debian

cf: https://docs.docker.com/engine/reference/commandline/build/#git-repositories

**Comment by menski** [comment]
> allows you to use the support in the 'docker build' command for branches/tags and folder

That is neat, wasn't aware of this feature. Thanks for pointing it out I will give it a try.

**Comment by AndreaGiardini** [comment]
Hello @chrismaeda and, first of all, apologies for the late answer :)

In the ticket that you linked, they suggest to install the package `libc6-compat` in order to get rid of the problems with netty-tcnative. Can you please let me know if that solves your problem?

**Comment by AndreaGiardini** [comment]
I've tried to run https://grpc.io/docs/quickstart/java/ in the docker container and indeed it doesn't work.
After installing the packages `libc6-compat gcompat` I got the examples working correctly

I would be in favor of adding these two packages to the image if you still need them since the change is way less invasive than changing the base image

**Comment by AndreaGiardini** [comment]
Hey @chrismaeda 
I am going to close this PR now since I provided a solution that (at least for me) works. Feel free to open a PR with my suggestion if that can help you :)

**Pull request closed without merging**
