### PR TITLE
chore(project): add docker compose alias for GHA

### PR DESCRIPTION
**Pull request by danielkelemen**
related to https://github.com/camunda/team-automation-platform/issues/180

### CODE REVIEW

**Comment by mboskamp** [comment]
@danielkelemen, are the two CI failures related to your changes?

**Comment by danielkelemen** [comment]
> @danielkelemen, are the two CI failures related to your changes?

@mboskamp, No but I'll run it once more. Wildfly is the slowest, it runs into timeout sometimes.

**Comment by mboskamp** [comment]
> Wildfly is the slowest, it runs into timeout sometimes.

Do you think it makes sense to increase the timeout?

**Comment by danielkelemen** [comment]
> Do you think it makes sense to increase the timeout?

@mboskamp, Yes, I think i'll increase it a bit, but I'll do it in a separate ticket.

**Review by mboskamp — APPROVED** [review]

**Pull request merged**
