### PR TITLE
Support Oracle JDBC Driver

### PR DESCRIPTION
**Pull request by ihostage**
Ideally, need to add Oracle 19 to [database settings in platform](https://github.com/camunda/camunda-bpm-platform/blob/master/database/pom.xml).
And if you have access to [Oracle DB Docker Image](https://hub.docker.com/_/oracle-database-enterprise-edition), need to add tests compose with Oracle DB as like Postgres and MySQL.

### CODE REVIEW

**Comment by ihostage** [comment]
Travis fails because on PR it does not access the repository with EE artifacts.

**Comment by AndreaGiardini** [comment]
Hello @ihostage 

Oracle 19 is currently not supported by Camunda, but Oracle 18 is.
If you can modify the PR to add Oracle 18 drivers we will add them to the docker image :)

**Comment by ihostage** [comment]
Hi, @AndreaGiardini! 👋 
It's a version of JDBC driver, not a Database. It's compatible with the previous version of Oracle Database.
See a question _"What is the JDBC and RDBMS interoperability matrix or the certification matrix?"_ on this [faq](https://www.oracle.com/database/technologies/faq-jdbc.html).
Recently Oracle did it 😄 It published JDBC driver to Maven Central 🎉 https://repo1.maven.org/maven2/com/oracle/ojdbc/
But it's only the latest `19.3.0.0`. Details on [this post](https://medium.com/@kuassimensah/oracle-jdbc-drivers-on-maven-central-64fcf724d8b).

**Comment by ihostage** [comment]
I tested Camunda docker image with 19.3.0.0 driver on our Oracle Database 12c and it works fine 👍

**Comment by ihostage** [comment]
Hi, @AndreaGiardini!
Can you review/merge this PR before release a 7.12.0?

**Review by lwille — APPROVED** [review]
hi @ihostage, thank you for your contribution and sorry for the long wait!
The EE build error is indeed caused on our side, we're going to fix that for future PRs.

**Pull request merged**
